#!/bin/bash -x

## xterm -fg white -bg black -e gdb --args

mpirun -n 1 ./ospExampleViewer --osp:module:dwdisplay --osp:device:dwdisplay ~/rs/intel/data/fiu-groundwater.xml : -n 1 ./dwDisplay --osp:module:dwdisplay --osp:device:dwdisplay